# permissions for end users to edit mariadbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadbcluster-editor-role
rules:
- apiGroups:
  - mariadb.mariadb.org
  resources:
  - mariadbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.mariadb.org
  resources:
  - mariadbclusters/status
  verbs:
  - get
