apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mariadb-list-pods
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-mariadb
subjects:
  - kind: ServiceAccount
    name: mariadb
roleRef:
  kind: Role
  name: mariadb-list-pods
  apiGroup: rbac.authorization.k8s.io