# permissions for end users to edit mariadbbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadbbackup-editor-role
rules:
- apiGroups:
  - mariadb.mariadb.org
  resources:
  - mariadbbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.mariadb.org
  resources:
  - mariadbbackups/status
  verbs:
  - get
