# permissions for end users to view mariadbusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadbuser-viewer-role
rules:
- apiGroups:
  - mariadb.mariadb.org
  resources:
  - mariadbusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mariadb.mariadb.org
  resources:
  - mariadbusers/status
  verbs:
  - get
