# permissions for end users to view mariadbbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadbbackup-viewer-role
rules:
- apiGroups:
  - mariadb.mariadb.org
  resources:
  - mariadbbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mariadb.mariadb.org
  resources:
  - mariadbbackups/status
  verbs:
  - get
