# permissions for end users to edit mariadbusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadbuser-editor-role
rules:
- apiGroups:
  - mariadb.mariadb.org
  resources:
  - mariadbusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.mariadb.org
  resources:
  - mariadbusers/status
  verbs:
  - get
