# permissions for end users to view MariaDBClusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: MariaDBCluster-viewer-role
rules:
- apiGroups:
  - mariadb.mariadb.org
  resources:
  - MariaDBClusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mariadb.mariadb.org
  resources:
  - MariaDBClusters/status
  verbs:
  - get
