
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mariadb.mariadb.org
  resources:
  - mariadbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.mariadb.org
  resources:
  - mariadbclusters/finalizers
  verbs:
  - update
- apiGroups:
  - mariadb.mariadb.org
  resources:
  - mariadbclusters/status
  verbs:
  - get
  - patch
  - update
