apiVersion: mariadb.mkaciuba.com/v1alpha1
kind: MariaDBCluster
metadata:
  name: cluster-sample
spec:
  primaryCount: 2
  dataStorageSize: 1G
  image: "ghcr.io/aldor007/mariadb-galera:1.0.3-34"
  storageClass: nfs-cubie2
  service:
      enabled: true
      loadbalancerIP: 10.39.39.39
      type: LoadBalancer
  rootPassword:
    name: mariadb-sample-root
    key: password
