apiVersion: mariadb.mariadb.org/v1alpha1
kind: MariaDBCluster
metadata:
  name: mariadbcluster-sample
spec:
  primaryCount: 2
  dataStorageSize: 1G
  image: "ghcr.io/aldor007/mariadb-galera:1.0.2-2"
  storageClass: nfs-cubie2
  rootPassword:
    name: mariadb-sample-root
    key: password
