apiVersion: mariadb.mkaciuba.com/v1alpha1
kind: MariaDBUser
metadata:
  name: mariadbuser-sample
spec:
  clusterRef:
    name: cluster-sample
    namespace: default
  user: mariadb-user
  password:
    name: mariadb-sample-root
    key: password
  allowedHosts:
    - "%"
  permissions:
    - schema: mariadb-test
      tables: [ "*" ]
      permissions:
        - ALL
