apiVersion: mariadb.mkaciuba.com/v1alpha1
kind: MariaDBBackup
metadata:
  name: mariadbbackup-sample
spec:
  clusterRef:
    name: cluster-sample
    namespace: default
  backupURL: s3://mkaciuba-backup/mariadb
  backupSecretName: s3-backup
