
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mariadb-operator.fullname" . }}-role
rules:
- apiGroups:
  - mariadb.mkaciuba.com
  resources:
  - MariaDBClusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.mkaciuba.com
  resources:
  - MariaDBClusters/finalizers
  verbs:
  - update
- apiGroups:
  - mariadb.mkaciuba.com
  resources:
  - MariaDBClusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - mariadb.mkaciuba.com
  resources:
    - mariadbclusters
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - mariadb.mkaciuba.com
  resources:
    - mariadbclusters/finalizers
  verbs:
    - update
- apiGroups:
    - mariadb.mkaciuba.com
  resources:
    - mariadbclusters/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
  - mariadb.mkaciuba.com
  resources:
  - mariadbbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.mkaciuba.com
  resources:
  - mariadbbackups/finalizers
  verbs:
  - update
- apiGroups:
  - mariadb.mkaciuba.com
  resources:
  - mariadbbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mariadb.mkaciuba.com
  resources:
  - mariadbdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.mkaciuba.com
  resources:
  - mariadbdatabases/finalizers
  verbs:
  - update
- apiGroups:
  - mariadb.mkaciuba.com
  resources:
  - mariadbdatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mariadb.mkaciuba.com
  resources:
  - mariadbusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.mkaciuba.com
  resources:
  - mariadbusers/finalizers
  verbs:
  - update
- apiGroups:
  - mariadb.mkaciuba.com
  resources:
  - mariadbusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups:
    - ""
  resources:
    - configmaps/status
  verbs:
    - get
    - update
    - patch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
- apiGroups:
    - "coordination.k8s.io"
  resources:
    - "leases"
  verbs:
    - "create"
    - "get"
    - "update"
- apiGroups:
  - apps
  resources:
    - statefulsets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - batch
  resources:
    - jobs
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - configmaps
    - events
    - jobs
    - persistentvolumeclaims
    - pods
    - secrets
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - pods/status
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - policy
  resources:
    - poddisruptionbudgets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - rbac.authorization.k8s.io
  - authorization.k8s.io
  resources:
    - '*'
  verbs:
    - '*'
- apiGroups:
    - "" # core
  resources:
    - serviceaccounts
  verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mariadb-operator.fullname" . }}-role-binding
  labels:
    {{- include "mariadb-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mariadb-operator.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "mariadb-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}